### PR TITLE
Add convenient base test classes to help users write async tests easier

### PR DESCRIPTION
**Pull request by matthewadams**
Just throwing this out there for you to consider.  It would've helped me save time.  Hoping it might save others time.

### CODE REVIEW

**Comment by matthewadams** [comment]
@jponge See the difference between https://github.com/SciSpike/vertx-junit5/blob/abstract-rxjava-vertx-test-classes/src/test/java/io/vertx/junit5/AbstractRxJavaExampleTest.java#L18 and https://github.com/SciSpike/vertx-junit5/blob/abstract-rxjava-vertx-test-classes/src/test/java/io/vertx/junit5/AbstractRxJavaExampleTest.java#L35.

Notice:
* No try/catch block necessary
* No need to instantiate your own `io.vertx.rxjava.core.Vertx` yourself
* No need to call `assertTrue(context.awaitCompletion(60, TimeUnit.SECONDS));`
* No need to `subscribe()` to `Single` or `Completable`

**Comment by vietj** [comment]
I believe that with the project reorg for Rx and Rx2, we should move all Rx related code to the vertx-rx-java and vertx-rx-java2 which contain already integration tests for rx and Vert.x supported components.

e.g @tsegismont will add an help for `vertx-sql` in these project for helping the management of transaction with RxJava and RxJava2.

That would be:

https://github.com/vert-x3/vertx-rx/tree/master/rx-java2/src/main/java/io/vertx/reactivex/junit5

instead of this project.

**Comment by vietj** [comment]
@jponge I'm saying that in case you eventually accept this PR of course

**Comment by jponge** [comment]
My concern with this PR is that it redoes everything the extension does,
and that is the preferred way of operating with VertxTestContext.

Le lun. 28 mai 2018 à 19:05, Julien Viet <notifications@github.com> a
écrit :

**Comment by matthewadams** [comment]
@jponge Please give a link that dinatrates the “preferred way of operating”.

**Comment by jponge** [comment]
Ah you are right, you provide utilities to deal with rx types.

**Comment by jponge** [comment]
@matthewadams Did you play with the testing helpers in RxJava? http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/subscribers/TestSubscriber.html / http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/observers/TestObserver.html / etc

**Pull request closed without merging**
